---
title: Site Leaf Test
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    is_post: true
lang: fr
name: samuel
email: your-email@example.com
description: Un test pour un site web perso sur site leaf
baseurl: 
url: 
twitter_username: samueleyre
github_username: samueleyre
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-bulma-theme
plugins:
- jekyll-feed
- jekyll-paginate
version:
  bulma: 0.6.2
  font-awesome: 5.0.9
navigation:
  github: samuel
  twitter: samuel
  facebook: samuel
  google: '113457032081840418568'
paginate: 5
excerpt_separator: "<!--more-->"
date_format: "%B %d, %Y"
sass:
  style: compressed
