---
title: Site Leaf Test
timezone: UTC
lang: fr
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: "samuel"
email: your-email@example.com
description: Un test pour un site web perso sur site leaf
baseurl: 
url: 
twitter_username: samueleyre
github_username: samueleyre
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-bulma-theme

plugins:
- jekyll-feed
- jekyll-paginate


version:
  bulma: 0.6.2 # This depend on "cdnjs.com"
  font-awesome: 5.0.9 # This depend on "use.fontawesome.com", also name version it without "v" prefix.

navigation:
  github: samuel
  twitter: samuel
  facebook: samuel
  google: 113457032081840418568

paginate: 5
excerpt_separator: <!--more-->
date_format: '%B %d, %Y' # See http://alanwsmith.com/jekyll-liquid-date-formatting-examples to more info

sass:
  style: compressed

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
      is_post: true